"""Action Catalog for Bus Switching Layouts

This module builds a catalog of *unitary bus switching actions* where each action
represents a full, atomic reconfiguration (layout) of a single substation's
switchable elements over its two busbars.

Key goals:
- Config-driven substation set and reduction mode (SYM, N0, N1)
- Exclude identity layouts (configurable)
- Stable ordering (deterministic indices)
- Easy future extension (line status toggles, multi-sub composites)
- Masking support (cooldowns / unsafe / illegal)

Assumptions & Notes:
- We assume `env.sub_info` is an iterable giving the number of elements per
  substation in topo_vect order; cumulative sums yield slices in observation.topo_vect.
- Element ordering inside a substation's topo slice is NOT strictly documented; we
  construct our own canonical ordering: (line_or, line_ex, gen, load) with ascending indices.
  Identity detection assumes this ordering; if actual topo_vect order differs, identity
  elimination still works logically because we derive the baseline buses per element using
  mappings by element type and index.
- Bus numbers in Grid2Op are 1 or 2. We store them directly.
- For cooldown masking we currently only check line switching cooldowns using
  `observation.time_before_cooldown_line`. Generators / loads typically have no cooldown
  for bus moves; placeholder hooks are provided.

Reduction Modes:
- SYM: Keep one representative per (A,B) partition under swapping A<->B.
- N0: For each non-empty bus subset S: |S|>=2 AND line_end_count(S)>=1
- N1: For each non-empty bus subset S: |S|>=2 AND line_end_count(S)>=2

Identity:
- If drop_identity=True we remove the layout matching the baseline topology (initial reset obs).

Extensibility Hooks:
- add_line_status_toggles(catalog, env): placeholder to append new non-topology actions
- compose_multi_substation(...): future composite generation

Author: Auto-generated by action space refactor assistant.
"""
from __future__ import annotations
from dataclasses import dataclass, field
from typing import List, Dict, Tuple, Iterable, Optional, Any
import numpy as np

# Type aliases
Element = Tuple[str, int]  # (etype, index) where etype in {"line_or","line_ex","gen","load"}
BusAssignment = Dict[Element, int]  # bus number 1 or 2

REDUCTION_SYM = "SYM"
REDUCTION_N0 = "N0"
REDUCTION_N1 = "N1"
VALID_REDUCTION = {REDUCTION_SYM, REDUCTION_N0, REDUCTION_N1}

@dataclass
class SubstationLayoutAction:
    """Represents one full bus layout for a single substation."""
    sub_id: int
    elements: List[Element]  # stable ordered list
    assignment: BusAssignment  # maps each element to bus 1 or 2
    # Precomputed quick access lists per type for faster mask evaluation
    line_or_indices: List[int] = field(default_factory=list)
    line_ex_indices: List[int] = field(default_factory=list)
    gen_indices: List[int] = field(default_factory=list)
    load_indices: List[int] = field(default_factory=list)

    def apply(self, action_space) -> Any:
        """Create a Grid2Op action applying this layout.
        Only set elements whose bus differs from current; we cannot know current
        here without observation, so we set all to target bus (Grid2Op will ignore if same).
        
        Special case: sub_id=-1 means do-nothing action.
        """
        action = action_space()
        
        # Handle do-nothing action
        if self.sub_id == -1:
            return action  # Empty action = do nothing
        
        if self.line_or_indices:
            action.line_or_set_bus = [(idx, self.assignment[("line_or", idx)]) for idx in self.line_or_indices]
        if self.line_ex_indices:
            action.line_ex_set_bus = [(idx, self.assignment[("line_ex", idx)]) for idx in self.line_ex_indices]
        if self.gen_indices:
            action.gen_set_bus = [(idx, self.assignment[("gen", idx)]) for idx in self.gen_indices]
        if self.load_indices:
            action.load_set_bus = [(idx, self.assignment[("load", idx)]) for idx in self.load_indices]
        return action

@dataclass
class ActionCatalog:
    actions: List[SubstationLayoutAction]
    per_sub_counts: Dict[int, int]
    reduction: str
    substations: List[int]
    drop_identity: bool
    # Derived maps
    per_sub_offsets: Dict[int, Tuple[int, int]] = field(default_factory=dict)
    # Cache of applied Grid2Op actions per action_space identity
    _applied_cache: Dict[int, List[Any]] = field(default_factory=dict, repr=False)

    def __post_init__(self):
        offset = 0
        for sub in self.substations:
            count = self.per_sub_counts.get(sub, 0)
            self.per_sub_offsets[sub] = (offset, offset + count)
            offset += count

    @property
    def size(self) -> int:
        return len(self.actions)

    def sub_catalog(self, sub_id: int) -> List[SubstationLayoutAction]:
        start, end = self.per_sub_offsets[sub_id]
        return self.actions[start:end]

    def get_applied_actions(self, action_space) -> List[Any]:
        """Return cached Grid2Op actions for this catalog and action_space.

        Creating Grid2Op Action objects is relatively expensive; MCTS builds
        legal actions many times per simulation step. Since applying a layout
        only depends on the action_space (not the observation), we can prebuild
        and reuse them safely across the search.
        """
        key = id(action_space)
        cached = self._applied_cache.get(key)
        if cached is not None and len(cached) == self.size:
            return cached
        # Build and cache
        applied: List[Any] = []
        for layout in self.actions:
            try:
                applied.append(layout.apply(action_space))
            except Exception:
                # Skip actions that fail to materialize for this action_space
                # Keep alignment by continuing; but to preserve indices, we still append do-nothing
                # Here we choose to skip entirely; train_agent maps by index from valid_actions anyway.
                pass
        self._applied_cache[key] = applied
        return applied

# =============================
# Catalog Construction
# =============================

def build_action_catalog(env, substations: Iterable[int], reduction: str, drop_identity: bool = True, 
                        include_do_nothing: bool = True) -> ActionCatalog:
    """Build the action catalog for the given substations and reduction mode.

    Parameters
    ----------
    env : grid2op.Environment
    substations : iterable of int
        Substation ids to include.
    reduction : str
        One of SYM, N0, N1.
    drop_identity : bool
        Whether to remove the baseline layout per substation.
    include_do_nothing : bool
        If True, prepend a do-nothing action at index 0.
    """
    if reduction not in VALID_REDUCTION:
        raise ValueError(f"Unknown reduction mode '{reduction}'. Valid: {VALID_REDUCTION}")

    # Acquire a baseline observation to detect identity layouts
    try:
        baseline_obs = env.reset()
    except Exception:
        baseline_obs = None

    actions: List[SubstationLayoutAction] = []
    per_sub_counts: Dict[int, int] = {}

    substations_sorted = sorted(set(substations))
    
    # Add do-nothing action at index 0 if requested
    if include_do_nothing:
        # Create a special do-nothing action (empty topology change)
        do_nothing = SubstationLayoutAction(
            sub_id=-1,  # Special marker for do-nothing
            elements=[],
            assignment={},
            line_or_indices=[],
            line_ex_indices=[],
            gen_indices=[],
            load_indices=[]
        )
        actions.append(do_nothing)
        per_sub_counts[-1] = 1  # Track do-nothing separately

    for sub_id in substations_sorted:
        sub_actions = _enumerate_substation_layouts(env, sub_id, reduction, drop_identity, baseline_obs)
        per_sub_counts[sub_id] = len(sub_actions)
        actions.extend(sub_actions)

    catalog = ActionCatalog(actions=actions,
                            per_sub_counts=per_sub_counts,
                            reduction=reduction,
                            substations=substations_sorted,
                            drop_identity=drop_identity)

    if catalog.size == 0:
        raise ValueError("Built catalog is empty. Check reduction mode and substation selection.")

    return catalog

# =============================
# Enumeration Helpers
# =============================

def _gather_substation_elements(env, sub_id: int) -> List[Element]:
    """Collect all switchable elements in a deterministic order.
    Order: line_or, line_ex, gen, load (ascending indices in each group)."""
    elements: List[Element] = []
    line_or_indices = np.where(env.line_or_to_subid == sub_id)[0]
    for idx in line_or_indices:
        elements.append(("line_or", int(idx)))
    line_ex_indices = np.where(env.line_ex_to_subid == sub_id)[0]
    for idx in line_ex_indices:
        elements.append(("line_ex", int(idx)))
    gen_indices = np.where(env.gen_to_subid == sub_id)[0]
    for idx in gen_indices:
        elements.append(("gen", int(idx)))
    load_indices = np.where(env.load_to_subid == sub_id)[0]
    for idx in load_indices:
        elements.append(("load", int(idx)))
    return elements

def _enumerate_substation_layouts(env, sub_id: int, reduction: str, drop_identity: bool, baseline_obs) -> List[SubstationLayoutAction]:
    elements = _gather_substation_elements(env, sub_id)
    n = len(elements)
    if n == 0:
        return []

    # Baseline bus assignment per element (fallback: all bus 1 if not derivable)
    baseline_assignment: Dict[Element, int] = {}
    if baseline_obs is not None and hasattr(baseline_obs, 'topo_vect') and hasattr(env, 'sub_info'):
        try:
            # Derive substation slice in topo_vect
            sub_counts = list(env.sub_info)
            # Assume sub_id indexes into sub_counts directly
            start = int(sum(sub_counts[:sub_id]))
            length = int(sub_counts[sub_id])
            sub_slice = baseline_obs.topo_vect[start:start+length]
            # We cannot reliably map each element type to an exact position; fallback: assign sequentially
            # in the same order we constructed elements.
            for i, el in enumerate(elements):
                if i < len(sub_slice):
                    baseline_assignment[el] = int(sub_slice[i])  # already 1 or 2
                else:
                    baseline_assignment[el] = 1
        except Exception:
            baseline_assignment = {el: 1 for el in elements}
    else:
        baseline_assignment = {el: 1 for el in elements}

    layouts: List[SubstationLayoutAction] = []

    # Enumerate all partitions (2^n). n kept small by reduction; if large, this could explode.
    for bitmask in range(1 << n):
        # Build assignment dict
        assignment: BusAssignment = {}
        for i, el in enumerate(elements):
            bus = 2 if (bitmask >> i) & 1 else 1
            assignment[el] = bus

        if drop_identity and all(assignment[el] == baseline_assignment.get(el, 1) for el in elements):
            continue  # Skip identity

        # Compute partition sets A (bus1) and B (bus2)
        bus1_elems = [el for el in elements if assignment[el] == 1]
        bus2_elems = [el for el in elements if assignment[el] == 2]

        if not _passes_symmetry(bus1_elems, bus2_elems, reduction, elements):
            continue
        if not _passes_reduction_rules(bus1_elems, bus2_elems, reduction):
            continue

        layout = _build_layout_action(sub_id, elements, assignment)
        layouts.append(layout)

    return layouts

def _passes_symmetry(bus1: List[Element], bus2: List[Element], reduction: str, ordered_elements: List[Element]) -> bool:
    """Always apply symmetry canonicalization for all reduction modes.

    Rationale: Even for N0 / N1 we want a stable, duplicate-free catalog where
    (A,B) and (B,A) are not both present. This preserves monotonic size
    relationships: SYM >= N0 >= N1.
    """
    key1 = tuple(bus1)
    key2 = tuple(bus2)
    return key1 >= key2

def _passes_reduction_rules(bus1: List[Element], bus2: List[Element], reduction: str) -> bool:
    if reduction == REDUCTION_SYM:
        return True  # No extra structural filtering

    def subset_ok(sub: List[Element]) -> bool:
        if len(sub) == 0:
            return True
        line_end_count = sum(1 for (t, _) in sub if t.startswith('line_'))
        if reduction == REDUCTION_N0:
            return len(sub) >= 2 and line_end_count >= 1
        if reduction == REDUCTION_N1:
            return len(sub) >= 2 and line_end_count >= 2
        return True

    return subset_ok(bus1) and subset_ok(bus2)

def _build_layout_action(sub_id: int, elements: List[Element], assignment: BusAssignment) -> SubstationLayoutAction:
    line_or_indices = [idx for (t, idx) in elements if t == 'line_or']
    line_ex_indices = [idx for (t, idx) in elements if t == 'line_ex']
    gen_indices = [idx for (t, idx) in elements if t == 'gen']
    load_indices = [idx for (t, idx) in elements if t == 'load']
    return SubstationLayoutAction(
        sub_id=sub_id,
        elements=list(elements),
        assignment=dict(assignment),
        line_or_indices=line_or_indices,
        line_ex_indices=line_ex_indices,
        gen_indices=gen_indices,
        load_indices=load_indices,
    )

# =============================
# Masking
# =============================

def compute_action_mask(observation, catalog: ActionCatalog) -> np.ndarray:
    """Compute a boolean mask (True = legal/keep) for the catalog based on cooldowns.

    Currently checks:
    - All involved lines have zero cooldown (time_before_cooldown_line == 0) for any change.
    - Placeholder hooks for future unsafe / islanding / security checks.

    If an action assigns a line end to the *same bus* it already is, we still allow it; we
    rely on drop_identity to remove pure no-ops. Mixed partial no-ops are fine.
    """
    size = catalog.size
    mask = np.ones(size, dtype=bool)

    # Fast path: required attributes missing -> return all True
    if not hasattr(observation, 'time_before_cooldown_line'):
        return mask

    line_cooldowns = observation.time_before_cooldown_line

    for idx, layout in enumerate(catalog.actions):
        # If any line end belongs to a line with cooldown, mask out.
        # We approximate: if either origin or extremity index appears and that line cooldown >0.
        # Need mapping from line end index to line id. In Grid2Op, line_or / line_ex indices are line ids.
        for line_id in layout.line_or_indices + layout.line_ex_indices:
            if line_id < len(line_cooldowns) and line_cooldowns[line_id] > 0:
                mask[idx] = False
                break
        # Future hooks:
        # if _would_be_unsafe(layout, observation): mask[idx] = False

    return mask

# Placeholder for future safety / power flow screening
# def _would_be_unsafe(layout: SubstationLayoutAction, observation) -> bool:
#     return False

# =============================
# Extensibility Hooks
# =============================

def add_line_status_toggles(catalog: ActionCatalog, env) -> None:
    """Placeholder: append line open/close actions to catalog (future)."""
    pass

def compose_multi_substation(catalog: ActionCatalog) -> None:
    """Placeholder: create composite actions spanning multiple substations (future)."""
    pass

# =============================
# Debug / Pretty Print
# =============================

def summarize_catalog(catalog: ActionCatalog) -> str:
    parts = [f"ActionCatalog: reduction={catalog.reduction} drop_identity={catalog.drop_identity} total={catalog.size}"]
    for sub in catalog.substations:
        parts.append(f"  Sub {sub}: {catalog.per_sub_counts.get(sub,0)} actions")
    return "\n".join(parts)

